// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbTDLsK4EXbFmaBibvYWP3_SBByM4uqlE',
    appId: '1:1085185077650:web:d6e703d2bdade5575cd14b',
    messagingSenderId: '1085185077650',
    projectId: 'mynotes-flutter-project-sl',
    authDomain: 'mynotes-flutter-project-sl.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-sl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmeTKMlBycMogMeEUn5FBDv150lUwy9jo',
    appId: '1:1085185077650:android:d0a6f13a6977f5035cd14b',
    messagingSenderId: '1085185077650',
    projectId: 'mynotes-flutter-project-sl',
    storageBucket: 'mynotes-flutter-project-sl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuC1Ykuz1_AC-iZsNewmY2Lhvz798wQlM',
    appId: '1:1085185077650:ios:c70aad89fd4941f05cd14b',
    messagingSenderId: '1085185077650',
    projectId: 'mynotes-flutter-project-sl',
    storageBucket: 'mynotes-flutter-project-sl.appspot.com',
    iosClientId: '1085185077650-1mllp2jdr0shij007bbr0r6cf7oveo6u.apps.googleusercontent.com',
    iosBundleId: 'com.sarralejmi.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuC1Ykuz1_AC-iZsNewmY2Lhvz798wQlM',
    appId: '1:1085185077650:ios:c70aad89fd4941f05cd14b',
    messagingSenderId: '1085185077650',
    projectId: 'mynotes-flutter-project-sl',
    storageBucket: 'mynotes-flutter-project-sl.appspot.com',
    iosClientId: '1085185077650-1mllp2jdr0shij007bbr0r6cf7oveo6u.apps.googleusercontent.com',
    iosBundleId: 'com.sarralejmi.mynotes',
  );
}
